import { CoachingEvent } from '../types/coaching';

// Events keyed to real segment IDs from segments.json.
// Timestamps sit ~600ms inside each segment window so the corner SVG overlay fires first.
export const MOCK_COACHING_EVENTS: CoachingEvent[] = [
  {
    id: 'evt_S27_braking_lap2',
    timestamp: 318800,
    corner_id: 'S27',
    severity: 'critical',
    message: 'Braking too late into the hairpin. You\'re arriving 18m past the marker — carry less speed in.',
    delta_time_loss: 0.41,
    category: 'braking',
  },
  {
    id: 'evt_S21_apex_lap2',
    timestamp: 242600,
    corner_id: 'S21',
    severity: 'warn',
    message: 'Running wide at apex. Clip the inside kerb earlier to open the exit.',
    delta_time_loss: 0.18,
    category: 'apex',
  },
  {
    id: 'evt_S29_throttle_lap2',
    timestamp: 332300,
    corner_id: 'S29',
    severity: 'warn',
    message: 'Throttle application hesitant on exit. Commit earlier — car is stable here.',
    delta_time_loss: 0.27,
    category: 'throttle',
  },
  {
    id: 'evt_S31_line_lap3',
    timestamp: 348500,
    corner_id: 'S31',
    severity: 'info',
    message: 'High-speed kink — track-out to the right edge fully on exit. You\'re leaving 0.2s on the table.',
    delta_time_loss: 0.20,
    category: 'racing_line',
  },
  {
    id: 'evt_S37_braking_lap3',
    timestamp: 424100,
    corner_id: 'S37',
    severity: 'critical',
    message: 'Brake balance too rearward. Front locking mid-corner — shift balance 2 clicks forward.',
    delta_time_loss: 0.55,
    category: 'braking',
  },
  {
    id: 'evt_S33_apex_lap3',
    timestamp: 393400,
    corner_id: 'S33',
    severity: 'info',
    message: 'Apex speed 8 km/h below reference. Trail brake deeper to rotate the car.',
    delta_time_loss: 0.14,
    category: 'apex',
  },
  {
    id: 'evt_S25_consistency_lap2',
    timestamp: 304800,
    corner_id: 'S25',
    severity: 'warn',
    message: 'Entry speed variance across laps is >12 km/h here. Commit to a fixed brake marker.',
    delta_time_loss: 0.22,
    category: 'consistency',
  },
  {
    id: 'evt_S39_throttle_lap3',
    timestamp: 438100,
    corner_id: 'S39',
    severity: 'info',
    message: 'Good rotation through the left hairpin. Roll onto throttle 0.3s earlier on exit.',
    delta_time_loss: 0.09,
    category: 'throttle',
  },
  {
    id: 'evt_S23_line_lap2',
    timestamp: 288000,
    corner_id: 'S23',
    severity: 'warn',
    message: 'Turn-in point too early. Straighten the entry to hit a later geometric apex.',
    delta_time_loss: 0.31,
    category: 'racing_line',
  },
  {
    id: 'evt_S35_consistency_lap3',
    timestamp: 410500,
    corner_id: 'S35',
    severity: 'info',
    message: 'Chicane rhythm is improving. Maintain this entry speed across the next 3 laps.',
    delta_time_loss: 0.00,
    category: 'consistency',
  },
];
